# Generated by Django 5.1.1 on 2024-11-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEM_MED', '0007_sideeffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideeffect',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
